### ISSUE TITLE
Prefer_dmy failing

### ISSUE THREAD

**Issue by EricSoroos** [dathere/datapusher-plus#141]
**Describe the bug**

qsv applydp 0.128.0 doesn't appear to support the `--prefer-dmy` flag, added here: https://github.com/dathere/datapusher-plus/blob/master/datapusher/jobs.py#L1120

qsv 0.108 seems to work, so I've downgraded there for now.

```
ckan@96a3a268e3a3:/$ /usr/local/bin/qsvdp applydp datefmt last_reported /tmp/tmp8xb42s2r.csv --output /tmp/tmpr0oz464i.csv --prefer-dmy
Unknown flag: '--prefer-dmy'

Usage:
qsv applydp operations <operations> [options] <column> [<input>]
qsv applydp emptyreplace --replacement=<string> [options] <column> [<input>]
qsv applydp dynfmt --formatstr=<string> [options] --new-column=<name> [<input>]
qsv applydp --help
ckan@96a3a268e3a3:/$ /usr/local/bin/qsvdp --version
qsvdp 0.128.0-mimalloc-Luau 0.625;polars-0.40.0;self_update-4-4;6.15 GiB-0 B-3.83 GiB-7.68 GiB (x86_64-unknown-linux-gnu compiled with Rust 1.78) prebuilt
```

**To Reproduce**
* with the environment of `PREFER_DMY=1`, upload a csv with date cols.

![image](https://github.com/dathere/datapusher-plus/assets/36156267/4876b30e-b9f3-469f-be81-644b8d42b2fc)

**Expected behavior**
Either `qsv applydp --prefer-dmy` works, or we just set the env variable.

**Desktop (please complete the following information):**
Looks like at least versions 0.16 -> master have this

**Comment by jqnatividad** [comment]
Thanks for the report @EricSoroos ,

I moved `datefmt` to its own command and removed it from `applydp`. I'll update DP+ so it can be used with the latest qsv.

**Comment by tino097** [comment]
@pdelboca @jqnatividad maybe we should create some version check and maybe displaying a message that newer QSV version has been released

**Comment by jqnatividad** [comment]
There is an existing minimal version check on DP+, but I agree that we can make DP+ aware of the maximum qsv version it can support too.

Now that the migration away from the deprecated ckanext-serviceprovider is largely done (thanks @tino097 ), I can start integrating the latest version of qsv for even more expanded analysis and metadata inferencing we've been busy baking in into qsv to fully realize [automagical metadata with the DRUF workflow](https://dathere.com/2023/11/automagical-metadata/). 😄
