### ISSUE TITLE
remove ckanserviceprovider dependency

### ISSUE THREAD

**Issue by jqnatividad** [dathere/datapusher-plus#66]
As per @amercader 's suggestion during the Feb 7 2023 tech team discussion, it's better to remove the dependency to simplify the architecture of Datapusher+, and make it more robust.

Perhaps, we can take another page from [XLoader](https://github.com/ckan/ckanext-xloader), and use its [simpler queuing tech](https://github.com/ckan/ckanext-xloader#simpler-queueing-tech) and get rid of the need to use a [separate web server](https://github.com/ckan/ckanext-xloader#separate-web-server).

**Comment by jqnatividad** [comment]
Most of the value add of DP+ is concentrated in changes in jobs.py.

Instead of getting rid of ckanserviceprovider, it may be easier to port the changes to a fork of xloader instead.

cc @tino097 @TomeCirun

**Comment by tino097** [comment]
@jqnatividad  so you are suggesting to use `xloader` instaed of `datapusher-plus` ?

**Comment by jqnatividad** [comment]
I'm thinking forking `xloader` and adding the `qsv`-powered stuff in jobs.py might be easier than removing the ckanserviceprovider dependency from DP+ and copying the xloader queueing stuff into DP+.

It'd still be DP+, but based forked from xloader...

**Comment by jqnatividad** [comment]
Nothing is that easy, but an initial inspection of xloader's jobs.py looks like a lot of the DP+ qsv stuff in its jobs.py can be ported over...

It will also make the task of making the Datastore Mgmt Interface easier, don't you think?

I'm also thinking of making it require Python3, so it will only support 2.9 and above...
