### ISSUE TITLE
Containerfile does miss GLIBCXX dependency

### ISSUE THREAD

**Issue by BonaBeavis** [dathere/datapusher-plus#75]
I have built 0.11.0, but pushing gives this error:

ckan@minipod_ckan:/$ /usr/local/bin/qsvdp
/usr/local/bin/qsvdp: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/bin/qsvdp)

**Comment by bluepython508** [comment]
I'm seeing this as well. It looks like it was probably introduced by updating `qsv` to 0.99, since the qsv builds updated the Ubuntu of the builder in [this commit](https://github.com/jqnatividad/qsv/commit/fbcf3305cb949893900b4c675cc4d0ae8b462eae), which is included in 0.99 but not 0.87.
