### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by jqnatividad** [dathere/datapusher-plus#8]
Create a reference container image for Datapusher+.  This is already WIP and being done by @ctrepka .

**Comment by categulario** [comment]
I have a container image already, maybe we can compare and improve

**Comment by categulario** [comment]
this is the [Containerfile](https://gitlab.com/CodeandoMexico/ckancontainers/-/blob/main/datapusher/Containerfile) and the rest of the support files needed. It wouldn't work as it is for this project, but I'll do a little effort to adapt it and submit a PR.

If a package is published to pypi (which is now possible thanks to #16) then the `Containerfile` can benefit from it and be simplified

**Comment by categulario** [comment]
In that same repo there's a complete base setup of CKAN with every service needed

**Comment by ctrepka** [comment]
@categulario thanks for sharing, and sorry I'm getting back to this so late. I started my containerization process today and you can find the codebase [here](https://github.com/ctrepka/docker-datapusher-plus)
